spring:
  application:
    name: hello
  datasource:
    url: jdbc:mysql://81.69.30.150:3307/test?allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: qiu123.
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 81.69.30.150
    password: qiu123.
    port: 6380
  jpa:
    show-sql: true
  rabbitmq:
    host: 81.69.30.150
    port: 5672
    username: admin
    password: admin
server:
  port: 8081